### PR TITLE
Tickets/dm 30739

### PR DESCRIPTION
**Pull request by wvreeven**
The deploy-condo-private, lsstsqre-private, the base components, M1M3 Support and PTG have been built. Missing still are the builds for lsst_sims, mtaos, scriptqueue, scheduler and Sal Sciplat.

### CODE REVIEW

**Comment by mareuter** [comment]
We have to hold off on this until we have completed the NTS installation and are ready for the summit.

**Review by tribeiro — CHANGES_REQUESTED** [review]
Need some input

**Comment by wvreeven** [comment]
I converted the PR to a draft pending deployment at the summit.

**Comment by tribeiro** [comment]
Instead of making it a draft and waiting for the summit deployment, create a `cycle/0021` branch  (based on master)  and make this PR against it. We can use the `cycle/0021` branch as reference until we do the deployment at the summit.

**Review by mareuter — APPROVED** [review]
All of the changes are in. Thanks for all the hard work.

**Review by tribeiro — APPROVED** [review]
Changes looks good!

**Pull request merged**
