### PR TITLE
DM-25505 Initial work on ts_cycle_build

### PR DESCRIPTION
**Pull request by tribeiro**
Add initial files for build at NCSA.

### CODE REVIEW

**Comment by mareuter** [comment]
First general comment: The yum repo file is repeated more than once in the repo. It would be nice if we could figure out how to only have one copy and everything just reference that.

**Comment by mareuter** [comment]
My second general comment: After thinking about the agreement to move Dockerfiles into the individual CSC repos, this system runs counter to that. I think I'm OK with reversing course if this system works out as I like the file containing the clear specification of versions being used. We should decide on this quickly because this does effect how the folks working on the Jenkins builds might have to retool the Docker part.

**Comment by tribeiro** [comment]
@mareuter I managed to unify the the use of the repo file. Really nice suggestion. Let me know if you have more comments.

**Comment by tribeiro** [comment]
> My second general comment: After thinking about the agreement to move Dockerfiles into the individual CSC repos, this system runs counter to that. I think I'm OK with reversing course if this system works out as I like the file containing the clear specification of versions being used. We should decide on this quickly because this does effect how the folks working on the Jenkins builds might have to retool the Docker part.

I am afraid I really don't have a good answer for this. I think we will need to experiment with it and see if it fits our purposes. If it works, then we can adopt it, having the docker files for the deployment build residing with this package rather than with the components.

**Pull request merged**
